### PR TITLE
Updates from master

### PR DESCRIPTION
**Pull request by andreyrd**
This is how you would update your personal branch to the latest code in master. Base is your branch, and compare is master. We'll have to see how well keeping personal branches will work, as it may get messy.

### CODE REVIEW

**Comment by bdubchambers** [comment]
As long as we keep our branches updated with the master, through the git app or through the console, we will be fine.  We just need to make sure we are not changing more than a couple things per each pull to master.  I only commited the readme with abandon because its just a readme (I won't be committing anything of substance without proper pull requests).

**Comment by andreyrd** [comment]
Alright, sounds good :)

**Comment by bdubchambers** [comment]
@andreyrd , I mean, it's much better than everyone manhandling the master (or a copy) and not using the git branching/issues tracking/pull request features, right?  Is there a better, more efficient way to do this that you have in mind?

**Comment by andreyrd** [comment]
This way is good, I'm just looking into how we can cleanly update our
personal branches from master.

For example, say person A merges some stuff into master from their personal
branch with a pull request. Then person B's personal branch is out of sync
with master.

I think we can use rebase to bring the personal branch up to date. I
haven't tried it yet, though.

**Comment by bdubchambers** [comment]
@andreyrd The easiest way to do this is with the Git App that has a Sync button in the upper right hand corner, and it gives you a comparison, and stays up to date letting you know if your branch falls out of sync with the master.  Everyone will know when a feature gets added through a Pull Request, because we will all approve it and discuss what it does and how.  In other words, everyone will be fully aware of a master change, and can just sync their branch, test, and then if something is broken they can change some code, or tell the author that they messed up and possibly revert the Pull with a simple button click.

**Pull request merged**
